services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file: ./server/.env
    expose:
      - "5000"
    depends_on:
      - mongo
      - redis
    # The healthcheck tells Docker to check if the backend is ready.
    # It attempts to connect to the backend's internal port.
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --timeout=1 http://localhost:5000/api/user/test || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./client
    container_name: frontend
    restart: always
    env_file: ./client/.env
    expose:
      - "3000"
    depends_on:
      - backend
    # The healthcheck tells Docker to check if the frontend is ready.
    # It attempts to connect to the frontend's internal port.
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --timeout=1 http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/ssl/certs:ro
      - ./certs:/etc/ssl/private:ro
    # Nginx now depends on the frontend and backend being healthy.
    # This prevents the 502 error by waiting for them to be fully ready.
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy

volumes:
  mongo_data:
  redis_data:
